language: generic
dist: bionic
services:
    - docker

before_install:
    - docker build -t viaches/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true viaches/docker-react npm run test